name: deployment
on:
  push:
    branches:
      - main
jobs:
  npm_job:
    runs-on: [padc]
    defaults:
      run:
        working-directory: /home/ubuntu/Task-Management
    steps:
      - name  : Reset changes
        run   : git reset --hard
      - name  : Check out the repo
        run   : git pull 
      - name  : Install npm
        run   : npm install
      - name  : Build code
        run   : npm run build
      - name  : Restart worker
        run   : |
                export PM2_HOME=/root/.pm2
                pm2 restart Task-Management
